### ISSUE TITLE
Mark old Ansible role repositories as obsolete, fix links in repo README

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/.github#2]
Every obsolete repository should have something like "this repo is obsolete since, please use new collection available here" in its README, these are:
 * https://github.com/nspcc-dev/ansible-neofs-http-gw
 * https://github.com/nspcc-dev/ansible-neofs-storage
 * https://github.com/nspcc-dev/ansible-neofs-rest-gw
 * https://github.com/nspcc-dev/ansible-neofs-ir
 * https://github.com/nspcc-dev/ansible-neofs-s3-gw

**Comment by 532910** [comment]
done

**Comment by roman-khimov** [comment]
Not exactly, we still have links to old repos on https://github.com/nspcc-dev/
