### ISSUE TITLE
Unified linter job

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/.github#21]
## Is your feature request related to a problem? Please describe.
One GO repo -- one linter job. Many repos -- many jobs. One change -- many PRs in every repo. Many repos -- one (almost) GO team with the same (almost) ways to write code.

## Describe the solution you'd like
Find out if it is possible to unify the linter action (and its settings).

## Describe alternatives you've considered
Do nothing.

## Additional context
DCO work done once: https://github.com/nspcc-dev/.github/pull/12, https://github.com/nspcc-dev/.github/pull/15.

**Comment by roman-khimov** [comment]
Can be started with several closely aligned (wrt linter settings) repos and then expanded.
