### ISSUE TITLE
Place for issue reference in commit message

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/.github#28]
## Current Behavior
Commit message guideline can be read as allowing `header: short message, fix №XYZ` or not
https://github.com/nspcc-dev/neo-go/pull/3526#discussion_r1694584915

## Expected Behavior
Some explicit specification.

## Possible Solution
Decide on whether it's allowed and document it.

**Comment by carpawell** [comment]
I would always place it in the body. No strict pros. Header says about the "code" thing to me, while body explains with some additional context (external refs).

**Comment by roman-khimov** [comment]
To me it's perfectly fine if it fits. Less lines, less things to think about.

**Comment by AnnaShaleva** [comment]
It's OK to me to use both ways. However, my *personal* preference matches @carpawell's opinion: use header for text description only, use body for links. It just looks more pretty to me, but it's an extremely subjective argument.
