### ISSUE TITLE
Change Go version support policy to -1 version

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/.github#30]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I see https://github.com/nspcc-dev/neo-go/pull/3428 or https://github.com/nspcc-dev/neofs-rest-gw/pull/230. It looks like we're a bit unsynchronized with the rest of the world wrt supported Go versions, everyone is doing "current + 1 previous" while we're trying to do "current + 2 previous".

Our policy tries to not push people too aggressively and handle Go updates in more convenient way (which is dependent on the way Go is installed). To me Go release policy is too aggressive on its own with 6 month cycles and 1y deprecation. Yet at the same time we see that usually people handle this fine, people put newer versions into `go.mod`, people use the latest and greatest. So maybe it's just not a problem and we can have "current +1" too.

Notice also that this would simplify testing, -1 version to run against.

## Describe the solution you'd like
Change policy to "current +1".

## Describe alternatives you've considered
Keep as is. Well, it works too in some ways.

**Comment by carpawell** [comment]
I tried to push this suggestion at least twice (was unlucky). 6 months/year/1 version/2 versions/fresh/old do not bother me, I only do not understand why we are trying to support versions that Go developers do not want to.

**Comment by smallhive** [comment]
I categorically agree with policy changing to `current + 1`

**Comment by AnnaShaleva** [comment]
Agree, actively developing projects use this strategy, and it allows to use new language features with minimized time delay.
