### ISSUE TITLE
README.md is long, no one will read it.

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/.github#8]
https://github.com/nspcc-dev looks like a white noise.
I believe no one will read it!
Take a look at other companies:
https://github.com/AxisCommunications
https://github.com/espressif
https://github.com/pcengines
https://github.com/nginxinc
https://github.com/intel
https://github.com/jitsi
https://github.com/armbian

Only _who we are_ and _what we are doing_ questions should be answered on this page.

**Comment by roman-khimov** [comment]
This is a perfect place to have some navigation around tens of our repositories. You can't do it when you have 1K+ of them, you don't need it if you have three. For us this can be done and it's effective, if you know what you're looking for you won't look at any README, if you don't --- the way we have it now can help.
